- package-lock.json
- renovate.json
Update Renovate automerge rules to ensure major linting/storybook dependencies don't get automerged.
> Update Renovate automerge rules

- src/features/fills/components/asset-amount.js
- src/features/fills/components/asset-amount.test.js
This PR fixes an issue which caused fills with an unknown asset (and therefore no asset amount) to throw an error.
> Handle unknown tokens on fill page

- src/components/charts-container.js
- src/features/dashboard/components/dashboard-metrics-carousel.js
- src/features/dashboard/components/dashboard-metrics.js
- src/features/dashboard/components/dashboard-page.js
- src/features/dashboard/components/fill-count-metric.js
- src/features/dashboard/components/fill-volume-metric.js
- src/features/dashboard/components/trade-volume-metric.js
- src/features/stats/hooks/use-network-stats.js
- src/features/stats/hooks/use-relayer-stats.js
- src/features/stats/models/stats-model.js
- src/features/stats/selectors.js
This PR makes a couple of small steps towards highlighting the distinction between fill and trade volume. Both stats are now shown on the dashboard, and dashboard charts have been renamed for clarity. Informative tooltips can be added in a future PR.
> Improve clarity around distinction between fill and trade volume

- src/features/metrics/components/network-fees-chart.js
- src/features/metrics/components/network-fees-chart.stories.js
- src/features/metrics/components/network-volume-chart.js
- src/features/metrics/components/network-volume-chart.stories.js
- src/features/metrics/components/token-volume-chart.js
- src/features/metrics/components/token-volume-chart.stories.js
- src/features/relayers/components/relayer-page.js
- src/features/relayers/components/top-relayers-chart.js
- src/features/relayers/components/top-relayers-chart.stories.js
- src/features/tokens/components/top-tokens-chart.js
- src/features/tokens/components/top-tokens-chart.stories.js
Charts without any data available currently look strange, and in some circumstances cause exceptions. This PR ensures they fallback gracefully by displaying a "No data available" message.
> Handle lack of chart data gracefully

- src/features/fills/components/fill-list.js
- src/features/fills/components/fill-page.js
- src/features/fills/components/recent-fills-item.js
This PR ensures consistent use of the fill `value` field rather than a mix of `value` and `amount`. The `amount` field was renamed a while ago to `value` and will be removed in the future.
> Deprecate fill amount in favor of value

- src/features/fills/components/fill-page.js
This PR refactors the fill page to use asset prices instead of makerPrice/takerPrice fields since these fields will be removed from the API soon.
> Refactor fill page to use asset price

- src/util/format-token.js
- src/util/format-token.test.js
This PR updates the formatToken util to ensure it works properly in a number of edge cases:
1) When the amount being formatted is precise to more than six decimal places
2) When the amount is null/undefined
3) When the amount is NaN
> Ensure the formatToken util works with edge cases

- src/components/content-header.js
- src/components/page-layout.js
- src/components/routes.js
- src/constants.js
- src/features/addresses/components/__snapshots__/address-link.test.js.snap
- src/features/addresses/components/address-link.js
- src/features/addresses/components/address-link.test.js
- src/features/addresses/components/address-page.js
- src/features/addresses/get-routes.js
- src/features/fills/components/fill-page.js
- src/features/metrics/components/address-metrics-chart.js
- src/features/metrics/components/address-metrics-tooltip.js
- src/features/metrics/components/address-metrics.js
- src/features/metrics/components/async-address-metrics-chart.js
- src/features/metrics/hooks/use-address-metrics.js
This PR introduces a new address page which serves as the dashboard for maker/taker addresses. This page can be used to browse transactions related to a particular maker/taker and view metrics.
Individual fills link to this page and an addresses overview page will be introduced in the future.
> Introduce address page

- src/features/tokens/components/token-list-item-volume.js
- src/features/tokens/components/token-list-item.js
- src/features/tokens/components/token-list.js
- src/features/tokens/components/token-page.js
- src/features/tokens/components/tokens-page.js
- src/features/tokens/hooks/use-token.js
- src/features/tokens/hooks/use-tokens.js
This PR updates the tokens page to include a time period filter. This allows users to view traded tokens with their associated stats for a number of different time periods.
> Add time period filter to tokens page

- src/features/fills/components/asset-amount.js
- src/features/metrics/components/network-fees-tooltip.js
- src/features/metrics/components/token-volume-tooltip.js
- src/features/tokens/components/token-amount.js
- src/features/tokens/components/token-list-item-volume.js
- src/features/tokens/components/top-tokens-tooltip.js
- src/util/format-token-amount.js
- src/util/format-token-amount.test.js
- src/util/format-token.js
- src/util/format-token.test.js
This PR ensures that the thousands separator is included when formatting token amounts. This helps to improve readability.
> Delimit thousands when formatting token amounts

- src/features/tokens/components/token-list-item.js
This PR improves the token type label on the tokens page by using the badge from the fill page. This makes it more visually appealing and easier to scan.
> Improve the token type label on tokens page

- config/jest/setup.js
- src/hooks/use-api.js
- src/util/build-api-url.js
- src/util/build-api-url.test.js
- src/util/call-api.js
This PR updates the useApi hook to handle cancellation of in-flight requests. This fixes an edge case whereby the user may see data from a previous long-running request, causing the UI and data to be out of sync.
> Update useApi hook to handle cancellation of in-flight requests

- renovate.json
This PR updates the Renovate config to prevent rebasing of stale PRs. This will reduce the number of builds going through Netlify where we're currently over the monthly limit being introduced in December.
> Stop rebasing stale Renovate PRs

- src/components/page-title-block.js
Some page layout titles overflows.
Before:
After:
*Notes:*
TitleContainer had media queries but I don't know why. I removed them and checked every page that uses PageLayout with title and everything looks good. If it's needed for something please write me
> Add word-break to page layout title

- src/features/fills/components/__snapshots__/fill-list-assets.test.js.snap
- src/features/fills/components/__snapshots__/recent-fills-list.test.js.snap
- src/features/fills/components/asset-label.js
- src/features/fills/components/recent-fills-item.js
- src/features/fills/components/recent-fills-list.js
- src/features/fills/components/recent-fills-list.test.js
- src/features/fills/components/recent-fills.js
- src/features/fills/prop-types.js
This PR fixes a small issue with the spacing after ERC-721 assets in the recent fills card. I've also increased test coverage to avoid a regression in the future.
> Fix spacing in recent fills card

- src/components/error-boundary.js
- src/components/no-results-message.js
- src/features/fills/components/fills-page.js
- src/features/fills/components/fills.js
- src/features/fills/hooks/use-fills.js
- src/features/fills/prop-types.js
- src/features/search/components/search-results.js
This PR introduces querystring parameters to the fills page for filtering. The parameters that have been added are:
* dateFrom
* dateTo
* protocolVersion
* relayer
* status
* token
These parameters will be used in a future PR to build out a filtering UI.
> Add filtering parameters to fills page

- src/features/metrics/components/async-protocol-metrics-chart.js
- src/features/metrics/components/protocol-metrics-chart.js
- src/features/metrics/components/protocol-metrics-tooltip.js
- src/features/metrics/components/protocol-metrics.js
- src/features/metrics/hooks/use-protocol-metrics.js
- src/features/network-overview/components/network-overview-page.js
- src/features/network-overview/components/top-protocols-card.js
- src/features/network-overview/components/top-protocols-chart.js
- src/features/network-overview/components/top-protocols.js
- src/styles/constants.js
This PR adds a protocol adoption chart to the network overview page which shows the adoption of protocol versions over time.
> Add protocol adoption chart to network overview

- src/components/icons/index.js
- src/components/icons/time-period-icon.js
- src/components/mobile-time-period-filter.js
- src/components/popout-time-period-selector.js
- src/components/sub-title.js
- src/constants.js
- src/features/metrics/components/network-metrics-chart.js
- src/features/metrics/components/network-metrics-tooltip.js
- src/features/metrics/components/network-metrics.js
- src/features/metrics/components/protocol-metrics-chart.js
- src/features/metrics/components/protocol-metrics-tooltip.js
- src/features/metrics/components/protocol-metrics.js
- src/features/network-overview/components/network-overview-page.js
- src/features/network-overview/components/network-overview-stats-carousel.js
- src/features/network-overview/components/network-overview-stats.js
- src/features/network-overview/components/top-protocols-chart-tooltip.js
- src/features/network-overview/components/top-protocols-chart.js
- src/features/network-overview/components/top-protocols.js
- src/features/network-overview/get-routes.js
- src/features/stats/components/protocol-fees-widget.js
This PR makes a number of improvements to the network overview page:
* Introduces a mobile time period filter
* Begins phasing out fill volume to avoid confusion
* Introduces an accumulated protocol fees widget
* Renames the page to "Network Insights"
> Make various improvements to the network overview page

- src/components/__snapshots__/app-layout.test.js.snap
- src/components/__snapshots__/footer.test.js.snap
- src/components/__snapshots__/page-not-found.test.js.snap
- src/components/link.js
- src/features/currencies/components/rates-provider.js
- src/features/currencies/hooks/use-fetch-rates.js
- src/features/fills/components/__snapshots__/asset-label.test.js.snap
- src/features/fills/components/__snapshots__/fill-details.test.js.snap
- src/features/fills/components/__snapshots__/fill-list-assets.test.js.snap
- src/features/fills/components/__snapshots__/fill-relayer-link.test.js.snap
- src/features/fills/components/__snapshots__/recent-fills-list.test.js.snap
- src/features/relayers/components/__snapshots__/relayer-list.test.js.snap
- src/features/traders/components/__snapshots__/trader-link.test.js.snap
- src/hooks/use-api.js
This PR replaces react-router links with standard anchors. The goal here is to collect better usage analytics since Netlify Analytics collects metrics using server-side page requests.
> Use standard anchors instead of react-router links

- src/components/routes.js
- src/constants.js
- src/features/asset-bridges/components/active-bridges-widget.js
- src/features/asset-bridges/components/asset-bridge-image.js
- src/features/asset-bridges/components/asset-bridge-list.js
- src/features/asset-bridges/components/asset-bridges-page.js
- src/features/asset-bridges/components/asset-bridging-metrics-chart.js
- src/features/asset-bridges/components/asset-bridging-metrics-tooltip.js
- src/features/asset-bridges/components/asset-bridging-metrics.js
- src/features/asset-bridges/components/asset-bridging-stats.js
- src/features/asset-bridges/components/bridged-trades-widget.js
- src/features/asset-bridges/components/bridged-volume-widget.js
- src/features/asset-bridges/components/mini-bridge-metrics-chart.js
- src/features/asset-bridges/components/mini-bridge-metrics.js
- src/features/asset-bridges/components/volume-share-widget.js
- src/features/asset-bridges/get-routes.js
- src/features/asset-bridges/hooks/use-asset-bridge-metrics.js
- src/features/asset-bridges/hooks/use-asset-bridges.js
- src/features/asset-bridges/hooks/use-asset-bridging-metrics.js
- src/features/asset-bridges/hooks/use-asset-bridging-stats.js
- src/features/header/components/mobile-navigation.js
- src/features/header/components/navigation.js
This PR introduces a new page for monitoring the trading activity of asset bridges. Each asset bridge on the new page represents a single bridging contract.
Some thoughts on how the feature could be improved in the future:
* Add the option to group bridges by type (e.g. Kyber, Uniswap etc.)
* Visualise bridging dominance over time
* Provide an option for users to manually identify unknown contracts
* Extract destinations from DEX Forwarder activity
> Add asset bridges page

- src/features/traders/components/mini-trader-metrics-chart.js
- src/features/traders/components/mini-trader-metrics.js
- src/features/traders/components/trader-list.js
- src/features/traders/components/traders-page.js
- src/features/traders/hooks/use-trader-metrics.js
This PR adds some additional charts to the traders page to provide greater insight into activity during the selected period. 
The charts are as follows:
* Active traders over time
* Maker-taker split
* Per trader volume trend
> Add charts to traders page

- src/components/percentage-change.js
- src/components/price-change.js
- src/features/asset-bridges/components/asset-bridging-stats.js
- src/features/asset-bridges/components/bridged-trades-widget.js
- src/features/asset-bridges/components/bridged-volume-widget.js
- src/features/asset-bridges/components/volume-share-widget.js
- src/features/fills/components/trade-count-widget.js
- src/features/fills/components/trade-volume-widget.js
- src/features/home/components/home-page-metrics-carousel.js
- src/features/home/components/home-page-metrics.js
- src/features/home/components/zrx-price-widget.js
- src/features/network-overview/components/network-overview-stats-carousel.js
- src/features/network-overview/components/network-overview-stats.js
- src/features/stats/components/protocol-fees-widget.js
- src/features/tokens/components/token-list-item.js
- src/features/tokens/components/token-page-title.js
- src/features/tokens/components/token-price-widget.js
- src/features/traders/components/active-traders-widget.js
This PR adds percentage change indicators to a bunch of stat widgets across the site.
> Add percentage change indicators to stat widgets

- .gitattributes
- src/components/__snapshots__/app-layout.test.js.snap
- src/components/sidebar.js
- src/features/advertising/components/side-banner-view.js
Fixes #978 
Also I added `.gitattributes` as in Prettier's docs https://prettier.io/docs/en/options.html#end-of-line . Without it git will automatically convert to CRLF on Windows and prettier will complain about it because since version 2, Prettier has default `endOfLine = lf`
Please verify that on macOS everything works as expected
> Fix sidebar horizontal scroll
