.travis.yml
Update Travis config to only build master branch and pull requests.
=> Update travis config to only build master branch

config/webpack/production.config.js, package-lock.json, package.json
Reverts 0xTracker/0x-tracker-client#299
=> Revert "Add Packtracker support"

src/features/metrics/hooks/use-network-metrics.js
This PR fixes an issue with relayer metrics reported in https://github.com/0xTracker/0x-tracker-api/issues/125
=> Fix issue in relayer metrics

.eslintrc.js, public/index.html, src/components/__snapshots__/app-layout.test.js.snap, src/components/header-actions.js, src/components/header.js, src/components/icons/index.js, src/components/icons/notifications-icon.js
This PR adds a notifications icon to the header which reveals updates via a changelog powered by Headway.
=> Add notifications icon to header

src/components/loading-indicator.js, src/components/loading-indicator.test.js, src/components/loading-page.test.js, src/features/relayers/components/relayer-list.js, src/features/relayers/components/relayer-page.js, src/features/tokens/components/tokens-loader.js, src/features/tokens/components/top-relayer-tokens.js, src/features/tokens/components/top-tokens.js, src/util/normalize-period.js, src/util/normalize-period.test.js, src/util/pretty-period.js
This PR reworks the TopTokens component to improve the efficiency of its data fetching. The previous version would load all tokens and stats, merge the data, and select the top five. This work is now done API side, helping to massively reduce response time/size.
=> Rework the TopTokens component data fetching

src/constants.js, src/features/addresses/components/address-list.js, src/features/addresses/components/address-volume-label.js, src/features/addresses/components/addresses-page.js, src/features/addresses/get-routes.js, src/features/addresses/hooks/use-addresses.js, src/features/addresses/prop-types.js
This PR introduces an addresses page (not yet linked to) which gives an overview of the top maker/taker addresses from the last 24 hours.
=> Introduce addresses page

src/components/async-time-period-selector.js, src/components/filter-header.js, src/components/number.js, src/components/page-header.js, src/components/page-layout.js, src/components/time-period-selector.js, src/features/addresses/components/address-list.js, src/features/addresses/components/addresses-page.js
This PR adds a time period filter to the addresses page which allows users to modify the reporting period for stats.
=> Add period filter to addresses page

package-lock.json, src/features/addresses/components/address-list.js, src/features/relayers/components/__snapshots__/relayer-list.test.js.snap, src/features/relayers/components/relayer-list.js, src/features/relayers/components/relayer-list.test.js, src/features/relayers/components/relayer-page.js, src/features/relayers/components/relayer-volume-label.js, src/features/relayers/components/relayers-page.js, src/features/relayers/hooks/use-relayers.js
This PR adds a time period filter to the relayers page, utilising the new V1 relayers API endpoint.
=> Add time period filter to relayers page

src/components/expandable-mobile-navigation-item.js, src/components/icons/chevron-up-icon.js, src/components/icons/index.js, src/components/mobile-menu-header.js, src/components/mobile-menu.js, src/components/mobile-menu.stories.js, src/components/mobile-navigation-link.js, src/components/mobile-navigation.js, src/components/mobile-search-form.js, src/components/mobile-sub-navigation.js, src/styles/constants.js
This PR introduces the concept of expandable items to the mobile menu and adds the network navigation item as seen on the desktop version of the site.
=> Add network navigation to the mobile menu

src/components/sub-navigation-parent.js, src/components/time-period-selector.js, src/features/currencies/components/currency-selector.js, src/features/currencies/prop-types.js, src/features/preferences/components/settings-dialog.js, src/features/relayers/components/relayers-page.js, src/features/tokens/components/tokens-page.js, src/features/traders/components/trader-type-selector.js, src/features/traders/components/traders-filter-dialog.js, src/features/traders/components/traders-filter.js, src/features/traders/components/traders-page.js, src/features/traders/hooks/use-traders.js, src/util/build-api-url.js, src/util/build-url.js
This PR adds the traders filter to the traders page, allowing users to filter traders by type (maker/taker).
#610
=> Implement trader type filter on traders page

src/features/traders/components/traders-filter-dialog.js
This PR adds a reset button to the traders filters dialog, allowing users to reset all the additional filters to defaults.
=> Add reset button to traders filters

src/components/filter-header.js, src/components/time-period-selector.js, src/features/traders/components/traders-filter-dialog.js, src/features/traders/components/traders-filter.js, src/features/traders/components/traders-page.js
This PR improves the traders filter UX by:
* Ensuring the filters are visible on all breakpoints
* Adding time period to the filters dialog
=> Improve traders filters UX

src/components/charts-container.js
This PR improves the charts UX by increasing contrast of links in charts containers. This helps user to quickly understand what chart is shown at a glance.
https://github.com/0xTracker/0x-tracker-client/issues/624
=> Increase tabs contrast in charts container

src/components/mobile-navigation.js, src/components/navigation.js, src/features/traders/components/traders-page.js
This PR modifies the wording around traders to be "Top Traders" rather than "Makers & Takers".
=> Modify traders wording

src/features/relayers/components/top-relayers-chart.js
This PR updates the top relayers chart font to match other charts on the site.
https://github.com/0xTracker/0x-tracker-client/issues/622
=> Fix font in top relayers chart

src/components/filter-button.js, src/features/traders/components/traders-filter-dialog.js, src/features/traders/components/traders-filter.js, src/features/traders/components/traders-filter.stories.js
This PR improves the filters UX by making it more obvious that additional filters have been applied.
=> Improve applied filters indicator

src/features/fills/components/fill-list.js
This PR removes the fees column from fill lists as per the criteria in #672
=> Remove fee column from fill list

src/features/fills/components/fill-details.js, src/features/fills/components/fill-details.stories.js, src/features/fills/components/fill-page.js, src/features/fills/prop-types.js
This PR makes the `makerFee` and `takerFee` fields optional on fee pages. This helps to pave the way for v3 which will use a `fees` field instead.
https://github.com/0xTracker/0x-tracker-client/issues/676
=> Make makerFee and takerFee optional on fee pages

src/constants.js, src/features/fills/components/__snapshots__/fill-details.test.js.snap, src/features/fills/components/fill-detail.js, src/features/fills/components/fill-details.js, src/features/fills/components/fill-details.stories.js, src/features/fills/components/fill-details.test.js
This PR adds support for a protocol fee to the fill detail page in preparation for V3.
#674
=> Add protocol fee support to fill detail page

src/components/__snapshots__/app-layout.test.js.snap, src/components/__snapshots__/footer.test.js.snap, src/components/footer.js, src/components/footer.test.js
This PR extends the footer to include links to the new documentation website.
=> Add additional links to footer

src/components/protocol-version-selector.js, src/features/fills/components/fill-details.js, src/features/fills/components/fill-status-selector.js, src/features/fills/components/fills-filter.js, src/features/relayers/components/relayer-selector.js
This PR adds asset bridge information to fill pages. It also fixes some prop type issues.
=> Add asset bridge info to fill pages

src/components/__snapshots__/loading-indicator.test.js.snap, src/components/chart-placeholder.js, src/components/icons/index.js, src/components/icons/reset-icon.js, src/components/loading-indicator.js, src/components/reset-chart-button.js, src/features/metrics/components/address-metrics-chart.js, src/features/metrics/components/address-metrics.js, src/features/metrics/components/network-metrics-chart.js, src/features/metrics/components/network-metrics.js, src/features/metrics/components/relayer-metrics-chart.js, src/features/metrics/components/relayer-metrics.js, src/features/metrics/components/token-volume-chart.js, src/features/metrics/components/token-volume.js, src/features/metrics/hooks/use-network-metrics.js, src/features/metrics/hooks/use-relayer-metrics.js, src/features/metrics/hooks/use-token-metrics.js, src/features/metrics/hooks/use-trader-metrics.js, src/hooks/use-api.js
This PR adds brush functionality to all the charts which allows users to zoom in to a specific time period.
=> Add time period brush to metrics charts

public/index.html, src/components/app-layout.js
Adds a Coinzilla header banner to test out how it looks. Unfortunately not possible to test locally.
=> Implement header banner

src/components/__snapshots__/page-layout.test.js.snap, src/components/loading-page.js, src/components/page-layout.js, src/components/page-not-found.js, src/components/page-title-block.js, src/components/responsive-time-period-filter.js, src/features/advertising/components/advertising-tooltip.js, src/features/advertising/components/side-banner.js, src/features/advertising/components/top-banner.js, src/features/advertising/constants.js, src/features/network-overview/components/network-overview-page.js, src/features/news/components/article-page.js, src/features/news/components/news-page.js
This PR introduces new sponsor banner slots which will eventually be auctioned off on Microsponsors.
=> Create sponsor banner slots

src/components/percentage-change.js, src/features/relayers/components/__snapshots__/relayer-list.test.js.snap, src/features/relayers/components/relayer-list.js, src/features/relayers/components/relayer-list.test.js, src/features/relayers/components/top-relayers-table.js
This PR adds percentage change indicators to relayer lists.
=> Add percentage change data to relayer lists

src/components/number.js, src/features/tokens/components/token-list-item-volume.js, src/features/tokens/components/token-list-item.js, src/features/tokens/components/top-tokens-table.js
=> Add change indicators to token lists

src/features/search/components/search-suggestion.js, src/features/search/hooks/use-autocomplete.js, src/features/traders/components/trader-list.js, src/features/traders/components/trader-overview-card.js, src/features/traders/components/trader-page.js
This PR updates various trader components to consume additional metadata:
* Image
* Description
* Website URL
=> Consume additional trader metadata

.gitattributes, src/components/__snapshots__/app-layout.test.js.snap, src/components/__snapshots__/footer.test.js.snap, src/components/sidebar.js, src/components/subscribe-panel.js, src/features/advertising/components/side-banner-view.js
=> Fix firefox scroll issue

public/index.html
Tested locally already, heap connection verified
=> Adding heap analytics

netlify.toml, src/components/__snapshots__/app-layout.test.js.snap, src/components/__snapshots__/footer.test.js.snap, src/components/footer.js
- Test deploy previews
- Add netlify config
=> testing deploy preview
